FROM openjdk:11
VOLUME /tmp

ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY moralityEducation-1.0-SNAPSHOT.jar moralityEducation.jar
COPY crownposci.com.jks crownposci.com.jks
COPY template.xlsx template.xlsx
COPY City.json City.json
EXPOSE 9102
ENTRYPOINT ["java","-jar","/moralityEducation.jar"]