server:
  port: 8081
spring:
  kafka:
    producer:
      bootstrap-servers: hadoop02:9092
      transaction-id-prefix: kafkaTx-
      # 开启事务时，必须设置为all
      acks: all
    consumer:
      # Kafka服务器
      bootstrap-servers: hadoop02:9092
      group-id: firstGroup