server:
  port: 8080

logging:
  config: classpath:logback.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/medical_treatment?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
    url: jdbc:mysql://localhost:3306/moral_education?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.10.13:3306/moral_education?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456

hysea:
  po:
    packages: com.hysea.*.domain